# This is a basic workflow to help you get started with Actions

name: Super-Linter

# Controls when the workflow will run
on: push

jobs:
  # This workflow contains a single job called "build"
    super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
       uses: github/super-linter@v4.9.7
       
     - name: Run Super-Linter
     uses: github/super-linter@v4.9.7
     env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
    
